#spring.datasource.url=jdbc:[Database]://localhost:8080 //[Database???]
#spring.datasource.username=[DB ???]
#spring.datasource.password=[DB ????]
#spring.datasource.driver-class-name=[JDBC ????]

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/